version: '3.8'

services:
  storm_app:
    image: public.ecr.aws/m0c5k4m4/storm:latest
    ports:
      - "5000:8501"
    env_file:
      - .env
    volumes:
      - storm_data:/app/DEMO_WORKING_DIR
    entrypoint: /bin/sh -c "\
      cd .streamlit && \
      echo 'OPENAI_API_KEY = \"${OPENAI_API_KEY:-}\"' >> secrets.toml && \
      echo 'AZURE_API_BASE = \"${AZURE_API_BASE:-}\"' >> secrets.toml && \
      echo 'AZURE_API_VERSION = \"${AZURE_API_VERSION:-}\"' >> secrets.toml && \
      echo 'BING_SEARCH_API_KEY = \"${BING_SEARCH_API_KEY:-}\"' >> secrets.toml && \
      echo 'GPT_35_NAME = \"${GPT_35_NAME:-}\"' >> secrets.toml && \
      echo 'GPT_4_NAME = \"${GPT_4_NAME:-}\"' >> secrets.toml && \
      cat secrets.toml && \
      cd .. && \
      . venv/bin/activate && \
      streamlit run storm.py"

volumes:
  storm_data:
